package ModuloPacientes;


import static Bitacora.AgregarBitacora.crearTransaccion;
import Controladores.TelefonoJpaController;
import Controladores.TutorpacienteJpaController;
import Entidades.Telefono;
import Entidades.Tutorpaciente;
import Singleton.EntityM;
import java.util.List;
import javax.persistence.EntityManager;
import javax.persistence.Query;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author oem
 */
public class CrearTutor extends javax.swing.JFrame {

    /**
     * Creates new form CrearTutor
     */
    public CrearTutor() {
        initComponents();
        this.setLocationRelativeTo(null);
        llenarTabla();
        cargarDatos();
    }
    
    //DECLARACION DE VARIABLES GLOBALES
    TutorpacienteJpaController controladorTutor = new TutorpacienteJpaController(EntityM.getEmf());
    TelefonoJpaController controladorTelefono = new TelefonoJpaController(EntityM.getEmf());
    DefaultTableModel rellenarTabla;
    Tutorpaciente tutorEditar;
    Telefono telefonoEditar;
    private EntityManager em = EntityM.getEm();
    
    //METODO PARA CARGAR TODOS LOS DATOS DE TABLA TUTORES
    private void llenarTabla() {
        try {
            rellenarTabla = (new DefaultTableModel(
                    null, new String[]{
                        "Id", "Nombre",
                        "Direccion","Telefono",
                        }) {
                Class[] types = new Class[]{
                    java.lang.String.class,
                    java.lang.String.class,
                    java.lang.String.class,
                    java.lang.String.class,
                };
                boolean[] canEdit = new boolean[]{
                    false, false, false,false
                };
                
                @Override
                public Class getColumnClass(int columnIndex) {
                    return types[columnIndex];
                }

                @Override
                public boolean isCellEditable(int rowIndex, int colIndex) {
                    return canEdit[colIndex];
                }
            });
            tablaTutor.setModel(rellenarTabla);
            tablaTutor.getColumnModel().getColumn(0).setMaxWidth(0);
            tablaTutor.getColumnModel().getColumn(0).setMinWidth(0);
            tablaTutor.getColumnModel().getColumn(0).setPreferredWidth(0);
            tablaTutor.getColumnModel().getColumn(0).setResizable(false);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.toString() + "error2");
        }
    }
    //METODO PARA CARGAR DATOS DE BUSQUEDA PERSONALIZADA
    private void cargarDatos(){
        Object o[] = null;
        int posicion = 0;
        Query query = em.createNativeQuery("SELECT tutorpaciente.*, telefono.Numero FROM tutorpaciente LEFT JOIN telefono ON tutorpaciente.id = telefono.TutorPaciente_id;");
        List<Object[]> listaDatos = query.getResultList();
        rellenarTabla = (DefaultTableModel)tablaTutor.getModel();
        for(Object[] lista : listaDatos){
            rellenarTabla.addRow(o);
            rellenarTabla.setValueAt(lista[0], posicion, 0);
            rellenarTabla.setValueAt(lista[1], posicion, 1);
            rellenarTabla.setValueAt(lista[2], posicion, 2);
            rellenarTabla.setValueAt(lista[3], posicion, 3);
            posicion++;
        }       
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        txtDireccion = new javax.swing.JTextField();
        txtTelefono = new javax.swing.JTextField();
        btnCrear = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaTutor = new javax.swing.JTable();
        txtBusqueda = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Nuevo tutor");

        jLabel2.setText("Nombre:");

        jLabel3.setText("Dirección:");

        jLabel4.setText("Teléfono:");

        txtDireccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDireccionActionPerformed(evt);
            }
        });

        btnCrear.setText("Crear");
        btnCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Filtro de búsqueda"));

        jButton3.setText("Buscar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        tablaTutor.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tablaTutor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tablaTutorMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(tablaTutor);

        txtBusqueda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBusquedaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 290, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3)
                    .addComponent(txtBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE))
        );

        jButton1.setText("Editar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtDireccion)
                                    .addComponent(txtTelefono, javax.swing.GroupLayout.DEFAULT_SIZE, 81, Short.MAX_VALUE))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnCrear, javax.swing.GroupLayout.DEFAULT_SIZE, 64, Short.MAX_VALUE)
                        .addGap(17, 17, 17)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnCrear, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtDireccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDireccionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDireccionActionPerformed

    private void txtBusquedaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBusquedaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBusquedaActionPerformed
    
    public String nombre,direccion,telefono;
    //AL PRESIONAR UN TUTOR DE LA TABLA PODRA SER MODIFICADO
    private void tablaTutorMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaTutorMousePressed
        // TODO add your handling code here:
        if(evt.getClickCount() > 1){
            int fila = tablaTutor.getSelectedRow();
            if(fila >= 0){
                try {
                    tutorEditar = new Tutorpaciente(Integer.parseInt(tablaTutor.getValueAt(fila, 0).toString()));
                    //telefonoEditar = new Telefono(tutorEditar.getId());
                    System.out.println(Integer.parseInt(tablaTutor.getValueAt(fila, 0).toString()));
                    txtNombre.setText(tablaTutor.getValueAt(fila, 1).toString());
                    nombre = txtNombre.getText();
                    txtDireccion.setText(tablaTutor.getValueAt(fila, 2).toString());
                    direccion = txtDireccion.getText();
                    txtTelefono.setText(tablaTutor.getValueAt(fila, 3).toString());
                    telefono = txtTelefono.getText();

                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null, e.getMessage());
                }
            }else{
                JOptionPane.showMessageDialog(null,"No ha seleccionado ninguna fila.");
            }
        }
    }//GEN-LAST:event_tablaTutorMousePressed
    //BOTON PARA CREAR UN NUEVO TUTOR
    private void btnCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearActionPerformed
        // TODO add your handling code here:
        if(txtNombre.getText().equals("") || txtDireccion.getText().equals("") || txtTelefono.getText().equals("") ){
            JOptionPane.showMessageDialog(null,"Error: Uno de los campos se encuentran vacíos.");
            crearTransaccion("Error creación de un nuevo tutor, uno o más campos se encontraban vacíos",2);
        }else{
            try{
                Tutorpaciente tutor = new Tutorpaciente ();
                tutor.setNombre(txtNombre.getText());
                tutor.setDireccion(txtDireccion.getText());
                
                //Query query = em.createNativeQuery("SELECT MAX(id) AS id FROM tutorpaciente;");
                //int id = query.getFirstResult()+1;
                Telefono telefono = new Telefono();
                if(txtTelefono.equals("")){
                    telefono.setNumero("0");
                }else{
                    telefono.setNumero(txtTelefono.getText());
                }
                telefono.setTutorPacienteid(tutor);
                

                controladorTutor.create(tutor);
                controladorTelefono.create(telefono);
                llenarTabla();
                cargarDatos();
                JOptionPane.showMessageDialog(null,"Se ha creado un nuevo registro.");
                crearTransaccion("Escritura tabla tutor,"+txtNombre.getText()+","+txtDireccion.getText()+","+txtTelefono.getText(), 1);
            }catch(Exception e){ JOptionPane.showMessageDialog(null, e.getMessage());}
            //-------------------------

            this.txtDireccion.setText("");
            this.txtNombre.setText("");
            this.txtTelefono.setText("");
        }
    }//GEN-LAST:event_btnCrearActionPerformed
    //BOTON QUE REALIZA LA BUSQUEDA PERSONALIZADA
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        llenarTabla();
        int posicion = 0;
        Object o[] = null;
        Query query = em.createNativeQuery("SELECT tutorpaciente.*, telefono.Numero FROM tutorpaciente LEFT JOIN telefono ON tutorpaciente.id = telefono.TutorPaciente_id WHERE tutorpaciente.Nombre LIKE '%"+txtBusqueda.getText()+"%';");
        List<Object[]> listaDatos = query.getResultList();
        rellenarTabla = (DefaultTableModel)tablaTutor.getModel();
        for(Object[] lista : listaDatos){
            rellenarTabla.addRow(o);
            rellenarTabla.setValueAt(lista[0], posicion, 0);
            rellenarTabla.setValueAt(lista[1], posicion, 1);
            rellenarTabla.setValueAt(lista[2], posicion, 2);
            rellenarTabla.setValueAt(lista[3], posicion, 3);
            posicion++;
        }    
    }//GEN-LAST:event_jButton3ActionPerformed
    //BOTON PARA MODIFICAR UN TUTOR
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        controladorTutor.actualizarTutor(txtNombre.getText(), txtDireccion.getText(), txtTelefono.getText(), tutorEditar.getId());
        llenarTabla();
        cargarDatos();
        crearTransaccion("Modificación tabla tutor, Nombre antiguo: "+nombre+" Nombre nuevo:"+txtNombre.getText()+",direccion antigua: "+direccion+" direccion nueva: "+txtDireccion.getText()+", telefono antiguo: "+telefono+"telefono nuevo: "+txtTelefono.getText(), 1);
        JOptionPane.showMessageDialog(null,"Se ha actulizado un registro exitosamente.");

        this.txtDireccion.setText("");
        this.txtNombre.setText("");
        this.txtTelefono.setText("");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        ClientePacientes clienteP = new ClientePacientes();
        clienteP.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CrearTutor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CrearTutor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CrearTutor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CrearTutor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CrearTutor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCrear;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaTutor;
    private javax.swing.JTextField txtBusqueda;
    private javax.swing.JTextField txtDireccion;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtTelefono;
    // End of variables declaration//GEN-END:variables
}
